require 'kramdown'

module KramdownHeaderLinksPatch
  def convert_header(el, indent)
    attr = el.attr.dup
    if @options[:auto_ids] && !attr['id']
      attr['id'] = generate_id(el.options[:raw_text])
    end

    if @options[:header_links] && attr['id'].length > 0
      link = Kramdown::Element.new(:a, nil, nil)
      link.attr['href'] = "##{attr['id']}"
      el.children.unshift(link)
    end

    @toc << [el.options[:level], attr['id'], el.children] if attr['id'] && in_toc?(el)
    level = output_header_level(el.options[:level])
    format_as_block_html("h#{level}", attr, inner(el, indent), indent)
  end
end

Kramdown::Options.define(:header_links, Kramdown::Options::Boolean, false, <<~EOF)
  Adds anchor tags to headers so that a permalink can be generated by
  clicking on the header.

  Default: false
EOF

Kramdown::Converter::Html.prepend(KramdownHeaderLinksPatch)
